### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by sourav-dey** [tomlau10/gcc-make-run#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [gcc-make-run](https://github.com/tomlau10/gcc-make-run) package 0.2.9

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:7

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at parse (path.js:952:5)
    at Object.make (/packages/gcc-make-run/lib/gcc-make-run.coffee:133:12)
    at /packages/gcc-make-run/lib/gcc-make-run.coffee:79:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:49.1.0 atom-gdb:toggle-breakpoint (span.line-number.cursor-line.linter-cursor-line.cursor-line-no-selection)
     -0:12.9.0 gcc-make-run:make-run (linter-decoration.linter-warning)
```

### Non-Core Packages

```
atom-format 1.0.8 
atom-gdb 0.6.0 
autocomplete-clang 0.10.0 
build-cmake 0.9.1 
busy-signal 1.3.0 
code-peek 1.4.17 
gcc-make-run 0.2.9 
intentions 1.1.2 
linter 2.1.2 
linter-clang 3.4.9 
linter-ui-default 1.2.1 
pretty-json 1.6.1 
xml-formatter 0.10.0 
```

**Comment by tomlau10** [comment]
ummm....
sorry but you did not `Enter steps to reproduce` :flushed: 

---
by just judging the stack trace
this is triggered by `tree view > file name > right click > make run`
but i cannot reproduce this error
can you provide the steps / screenshot of what you click such that this error occur?

**Comment by sourav-dey** [comment]
Hey,
   It was due to the gdb-debugger package that I installed. Apparently, after installing that package -> adding breakpoints -> then running make-run caused that problem. There might be some weird mismatch happening between the two packages. I deleted gdb-debugger and it works great.

You can go ahead and close the issue, or if you are interested in whats the dependancy that caused this, I can reinstall gdb-debugger and get a more detailed answer.

Thanks & Regards,
Sourav
