### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by hanxuanliang** [tomlau10/gcc-make-run#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [gcc-make-run](https://github.com/tomlau10/gcc-make-run) package 0.2.11

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at exports.exec (child_process.js:120:18)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at Object.run (/packages/gcc-make-run/lib/gcc-make-run.coffee:172:5)
    at Object.compile (/packages/gcc-make-run/lib/gcc-make-run.coffee:136:8)
    at /packages/gcc-make-run/lib/gcc-make-run.coffee:87:75)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.2/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.2/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.2/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:30.6.0 core:move-right (input.hidden-input)
     -3:21.5.0 core:move-down (input.hidden-input)
     -3:13.1.0 core:move-right (input.hidden-input)
     -3:07.8.0 docblockr:parse-enter (input.hidden-input)
     -3:07.8.0 editor:newline (input.hidden-input)
     -2:55.1.0 docblockr:parse-enter (input.hidden-input)
     -2:55.1.0 editor:newline (input.hidden-input)
     -2:53.5.0 autocomplete-plus:confirm (input.hidden-input)
     -2:53.5.0 snippets:expand (atom-text-editor.editor.is-focused)
  2x -2:49.5.0 core:backspace (input.hidden-input)
  5x -2:40.2.0 core:move-right (input.hidden-input)
     -2:34.9.0 intentions:highlight (input.hidden-input)
     -2:34.5.0 core:save (input.hidden-input)
  3x -2:32.2.0 gcc-make-run:compile-run (input.hidden-input)
  2x -0:37.1.0 tree-view:remove (div.tool-panel.tree-view)
  2x -0:24 gcc-make-run:compile-run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-html-preview 0.1.22 
atom-material-ui 2.0.4 
autocomplete-paths 2.8.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.11 
gcc-make-run 0.2.11 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-clang 4.1.2 
linter-gcc 0.7.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.7 
minimap 4.29.6 
project-manager 3.3.5 
```

**Comment by tomlau10** [comment]
could you provide more information on how to reproduce this?

eg:
- using right click or shortcut to trigger the compile run
- screen capture of the package's config
- the content of file

**Comment by hanxuanliang** [comment]
When scanf function appears, it will be wrong. Maybe my configuration path is out of order
