### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setText' of undefined

### ISSUE THREAD

**Issue by kebien6020** [tomlau10/gcc-make-run#27]
Steps to reproduce:
Press Ctrl + F6 (with or without .cpp Makefile or other file opened)

**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Windows 10
**Thrown From**: [gcc-make-run](https://github.com/tomlau10/gcc-make-run) package 0.2.11

### Stack Trace

Uncaught TypeError: Cannot read property 'setText' of undefined

```
At C:\Users\Kevin\.atom\packages\gcc-make-run\lib\gcc-make-run-view.coffee:78

TypeError: Cannot read property 'setText' of undefined
    at RunOptionsView.module.exports.RunOptionsView.restoreOptions (/packages/gcc-make-run/lib/gcc-make-run-view.coffee:78:24)
    at RunOptionsView.module.exports.RunOptionsView.showRunOptions (/packages/gcc-make-run/lib/gcc-make-run-view.coffee:67:6)
    at /packages/gcc-make-run/lib/gcc-make-run-view.coffee:44:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:39.4.0 gcc-make-run:run-options (input.hidden-input)
  2x -0:38 intentions:highlight (input.hidden-input)
     -0:35.7.0 gcc-make-run:run-options (input.hidden-input)
  9x -0:31.2.0 intentions:highlight (input.hidden-input)
     -0:30.5.0 gcc-make-run:run-options (input.hidden-input)
     -0:27 editor:consolidate-selections (input.hidden-input)
     -0:27 core:cancel (input.hidden-input)
     -0:25.7.0 intentions:highlight (input.hidden-input)
     -0:25.4.0 gcc-make-run:run-options (input.hidden-input)
     -0:23.2.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:22.4.0 intentions:highlight (input.hidden-input)
     -0:22.2.0 gcc-make-run:run-options (input.hidden-input)
     -0:20.1.0 core:cancel (a.btn-issue.btn.btn-error)
     -0:19.2.0 gcc-make-run:run-options (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.7.0 core:cancel (a.btn-issue.btn.btn-error)
     -0:09.0 gcc-make-run:run-options (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-handlebars 1.3.0 
atom-jade 0.3.0 
atom-terminal 0.8.0 
atom-typescript 11.0.7 
atom-wrap-in-tag 0.6.0 
blade-snippets 0.2.0 
busy-signal 1.4.3 
clang-tools-extra 0.1.0 
emmet 2.4.3 
gcc-make-run 0.2.11 
goto-definition 1.3.4 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-babel 2.72.0 
language-batch 0.4.0 
language-blade 0.34.0 
language-haskell 1.13.2 
language-javascript-jsx 0.3.7 
language-lisp 0.2.0 
language-lua 0.9.11 
language-powershell 4.0.0 
language-pug 0.0.21 
language-tsql 0.19.0 
language-vue 0.23.1 
line-ending-selector-unix 0.0.9 
linter 2.2.0 
linter-clang 4.1.2 
linter-eslint 8.2.1 
linter-handlebars 2.5.0 
linter-jsonlint 1.3.0 
linter-phpcs 1.6.7 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.7 
terminal-plus 0.14.5 
```

**Comment by tomlau10** [comment]
seems some api related to `atom-text-editor` html element changed after atom 1.19 :thinking: 
will fix this soon
