### ISSUE TITLE
Failed to load the gcc-make-run package

### ISSUE THREAD

**Issue by ravindrashukla-ari** [tomlau10/gcc-make-run#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gcc-make-run](https://github.com/tomlau10/gcc-make-run) package 0.2.12

### Stack Trace

Failed to load the gcc-make-run package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/Downloads/atom-windows/Atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/Downloads/atom-windows/Atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/Downloads/atom-windows/Atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run-view.coffee:8:13)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run-view.coffee:1:1)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run-view.coffee:1:1)
    at Module.get_Module._compile (~/Downloads/atom-windows/Atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/Downloads/atom-windows/Atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/Downloads/atom-windows/Atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run.coffee:7:18)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run.coffee:1:1)
    at /packages/gcc-make-run-0.2.12/lib/gcc-make-run.coffee:1:1)
    at Module.get_Module._compile (~/Downloads/atom-windows/Atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/Downloads/atom-windows/Atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/Downloads/atom-windows/Atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/Downloads/atom-windows/Atom/resources/app/src/package.js:903:35)
    at ~/Downloads/atom-windows/Atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/Downloads/atom-windows/Atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/Downloads/atom-windows/Atom/resources/app/src/package.js:144:18)
```

### Commands

```
```

### Non-Core Packages

```
gcc-make-run 0.2.12 
```

**Comment by tomlau10** [comment]
I know it's a bit late as Atom had been discontinued for more then a year ago, and I have switched to VS Code for quite long. But recently I discovered that there is a **[Pulsar Editor](https://pulsar-edit.dev/)** which is a fork of Atom and can install atom extensions, I just tried it out on my win10 PC and installed this extension without any issue. Seems cannot reproduce it. 😕
